name: Build APK

on:
  workflow_dispatch:

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip libgl1-mesa-dev
          python3 -m pip install --upgrade pip
          pip install buildozer cython

      - name: Create buildozer.spec
        run: |
          cat > buildozer.spec <<EOF
          [app]
          title = MegaCalc
          package.name = megacalc
          package.domain = org.example
          source.dir = .
          source.include_exts = py,kv,png,jpg,atlas
          version = 1.0
          requirements = python3,kivy
          orientation = portrait

          [buildozer]
          log_level = 2
          warn_on_root = 0
          EOF

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: megacalc-apk
          path: bin/*.apk
